### PR TITLE
Added Github CI

### PR DESCRIPTION
**Pull request by graysuit**
Online compiler would automatically compile your code and return binary releases embed in to zip.
See builds:
https://github.com/graysuit/PEunionUnpacker/actions

And also I noticed dnlib and .net transition from filepath.
More better was is to use nuget package manager.

### CODE REVIEW

**Comment by miso-xyz** [comment]
i don't want to deal with online compilers, i prefer building stuff myself & provide virus scans instead of having github to do it.

**Comment by graysuit** [comment]
Its your right,
But actually, this would help you save your time.
Whenever you change x in code, it would instantly compile and give you binaries. 
Whereas, about virus results, you can use virustotal api to scan online resource free:

`https://www.virustotal.com/gui/url/` + SHA256(release_link_here) + `/detection`

for example:
`https://www.virustotal.com/gui/url/d344e9f3002cdc3bf49c05e3333698d5c1b844fee4b63bcc442f88329538b499/detection`

But anyway, you can do as wish.

**Comment by miso-xyz** [comment]
it doesn't, since im building to test stuff, then when everything is working i just upload it.

**Comment by graysuit** [comment]
lol. It isn't a big problem. You can give link to stable release at github action. And other github actions would have nightly builds.

**Pull request closed without merging**
